language: julia

os:
  - linux
  - osx

julia:
  - 0.4
  - 0.5
  - nightly

notifications:
  email: false

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'include(Pkg.dir("Highlights", "docs", "make.jl"))'
  - julia -e 'include(Pkg.dir("Documenter", "test", "coverage.jl"))'
